# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d4217eecf0e74f9d59133ff0813a2cbaacdf4507c38ad1743f2750e0663c4e22e2713c4c57d74b0351c861c46e3e7a2560a33ff46e1a95507a8a629f57b227

test:
  secret_key_base: e72eef52394aa70720fdbc84873db965b3e77a124c7966d392f51457036aa338e149acce66b043b21efee92a533f3c3e52aaf1e14dbc3098f9438b56e69c65b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
